# Generated by Django 6.1.2 on 2026-10-10 05:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_app', '0002_category_record_created_by_alter_record_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('zone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedClock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('current_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('capacity_kg', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity_kg', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pickup_from', models.DateTimeField()),
                ('pickup_until', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='hackathon_app.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('planned_pickup_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COLLECTED', 'Collected'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], default='ACTIVE', max_length=20)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='hackathon_app.donation')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='hackathon_app.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=30)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permitted_zones', to='hackathon_app.volunteer')),
            ],
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['pickup_until'], name='hackathon_a_pickup__bda3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor'], name='hackathon_a_donor_i_3efb4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_kg__gte', 1)), name='donation_quantity_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_from__lt', models.F('pickup_until'))), name='donation_pickup_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['donation', 'status'], name='hackathon_a_donatio_ef0165_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['volunteer', 'status'], name='hackathon_a_volunte_4c7253_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['planned_pickup_at'], name='hackathon_a_planned_bfd4b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_kg__gte', 1)), name='claim_quantity_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'COLLECTED', 'CANCELLED', 'MISSED'])), name='claim_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='volunteerzone',
            constraint=models.UniqueConstraint(fields=('volunteer', 'zone'), name='unique_volunteer_zone'),
        ),
    ]
